theme: jekyll-theme-hacker
title: Eleanor Swift
description: Dedicated second-year Computer Science student at Meadowbrook University, with a passion for crafting innovative software solutions and a commitment to fostering STEM education through hackathons and other tech ventures. Actively searching for Summer and Fall internship opportunities in 2024. 
