theme: jekyll-theme-hacker
title: Eleanor Swift
description: Dedicated second-year Computer Science student at Meadowbrook University, with a passion for crafting innovative software solutions and a commitment to fostering STEM education through volunteering and hackathon participation.
